[package]
name = "cargo-quickbuild"
version = "0.0.0"
authors = ["David Laban <david.laban@red-badger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]