[package]
name = "cargo-quickbuild"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo_metadata = "0.14.2"
guppy = "0.13.0"
tempdir = "0.3.7"
