[package]
name = "cargo-quickbuild"
version = "0.0.0"
authors = ["David Laban <david.laban@red-badger.com>"]
edition = "2018"

[dependencies]
cargo-lock = { version = "6.0.1", features = ["dependency-tree"] }
petgraph = "*"
sha2 = "0.9.3"
globwalk = "0.8.1"
