# cc 1.0.73
cc_1_0_73 = { package = "cc", version = "=1.0.73", features = ["jobserver", "parallel"], default-features = false }
jobserver_0_1_24 = { package = "jobserver", version = "=0.1.24", features = [], default-features = false }
libc_0_2_125 = { package = "libc", version = "=0.2.125", features = ["default", "std"], default-features = false }
